### ISSUE TITLE
Type/Pillar Information in Detail Dashboard

### ISSUE THREAD

**Issue by gmmurugan** [tensult/cloud-reports#10]
Need to have the type(pillar) of the analysed data in the detail dashboard to filter say security alone.

    Informational = "Informational",
    Security = "Security",
    Reliability = "Reliability",
    PerformanceEfficiency = "PerformanceEfficiency",
    CostOptimization = "CostOptimization",
    OperationalExcellence = "OperationalExcellence",

**Comment by koladilip** [comment]
I have added this feature, try with the latest code.
