### ISSUE TITLE
Task not complete - HTML report

### ISSUE THREAD

**Issue by cloudgprabhu** [tensult/cloud-reports#18]
Hello,

I have run the command to pull the data in html format... but it freeze as below and did not return any errors... 

...
...
...
...
aws.elb.ElbV2sCollector completed
aws.sns.TopicsDetailsCollector completed
aws.sqs.QueueUrlsCollector completed
aws.sqs.QueueAttributesCollector completed
aws.elb.ElbV2AttributesCollector completed
aws.elb.ElbV2ListenersCollector completed
aws.lambda.LambdaFunctionVersionsCollector completed
{}
{}
arn:aws:elasticloadbalancing:us-east-1:AccountNo:loadbalancer/net/awseb-AWSEB-10XXGPWFPRTWZ/78600ae2737bbf1f
arn:aws:elasticloadbalancing:us-east-1:AccountNo:loadbalancer/net/awseb-AWSEB-19JIMP19V4DZH/874541c9e9f3c57a
arn:aws:elasticloadbalancing:us-east-1:AccountNo:loadbalancer/net/awseb-AWSEB-1EEOAZO1NP4JJ/9a8edf99a69e0d36
arn:aws:elasticloadbalancing:us-east-1:AccountNo:loadbalancer/net/awseb-AWSEB-12TFJ327CT65O/a53d99ef09622732
{}
{}
arn:aws:elasticloadbalancing:us-west-2:AccountNo:loadbalancer/net/awseb-AWSEB-WCBOKYEK6ET9/2dd6436611b1c45a
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}

**Comment by koladilip** [comment]
How long it got stuck?

**Comment by cloudgprabhu** [comment]
I waited 30 mins... then I re-executed and the url opened in the browser using localhost:3000 ! we cannot save the HTML format? that looks pretty awesome!

**Comment by koladilip** [comment]
You can try csv or pdf formats too. Incase you need to send report to anyone.


________________________________

**Comment by koladilip** [comment]
Please check now by git pulling the code again. I have added wait time so to avoid throttling.
