### ISSUE TITLE
npm error when trying to build the package

### ISSUE THREAD

**Issue by sathyajackson** [tensult/cloud-reports#3]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'scan' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prescan', 'scan', 'postscan' ]
5 info lifecycle cloud-reports@0.5.0~prescan: cloud-reports@0.5.0
6 silly lifecycle cloud-reports@0.5.0~prescan: no script for prescan, continuing
7 info lifecycle cloud-reports@0.5.0~scan: cloud-reports@0.5.0
8 verbose lifecycle cloud-reports@0.5.0~scan: unsafe-perm in lifecycle true
9 verbose lifecycle cloud-reports@0.5.0~scan: PATH: /usr/share/npm/bin/node-gyp-bin:/root/scripts/cloud-reports/node_modules/.bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle cloud-reports@0.5.0~scan: CWD: /root/scripts/cloud-reports
11 silly lifecycle cloud-reports@0.5.0~scan: Args: [ '-c', 'node dist/scan.js' ]
12 silly lifecycle cloud-reports@0.5.0~scan: Returned: code: 1  signal: null
13 info lifecycle cloud-reports@0.5.0~scan: Failed to exec scan script
14 verbose stack Error: cloud-reports@0.5.0 scan: `node dist/scan.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cloud-reports@0.5.0
16 verbose cwd /root/scripts/cloud-reports
17 error Linux 4.4.0-43-Microsoft
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "scan"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error cloud-reports@0.5.0 scan: `node dist/scan.js`
22 error Exit status 1
23 error Failed at the cloud-reports@0.5.0 scan script 'node dist/scan.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cloud-reports package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/scan.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cloud-reports
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cloud-reports
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by koladilip** [comment]
Can you please tell me what commands are you running?

**Comment by sathyajackson** [comment]
npm run build and the above log is npm-debug logs.

npm run build is getting failed with package version mismatch

**Comment by koladilip** [comment]
which operating system are you using?

**Comment by sathyajackson** [comment]
ubuntu, I think I found the issue, its rights now installing the packages, will update you if I find any more errors.

**Comment by sathyajackson** [comment]
I got the packages to install, after which when i run a sample module ec2 i end with below error.

aws.ec2.TerminationProtectionCollector completed
(node:2897) UnhandledPromiseRejectionWarning: Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:2897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)

npm ERR! Linux 4.4.0-43
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "scan" "--" "--profile" "default" "--module" "ec2"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cloud-reports@0.5.0 scan: `node dist/scan.js "--profile" "default" "--module" "ec2"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloud-reports@0.5.0 scan script 'node dist/scan.js "--profile" "default" "--module" "ec2"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cloud-reports package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/scan.js "--profile" "default" "--module" "ec2"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cloud-reports
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cloud-reports
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by koladilip** [comment]
I have added try catch for all collectors, check now.
