### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by sathyajackson** [tensult/cloud-reports#5]
Not sure what is worng, i again tried to build the same repo on a different machine which is running ubuntu 18 and i am again facing the same issue. This time my workaround dint work and not sure if there are conflict with package. I have no knowledge on nodejs, so please help.

> cloud-reports@0.5.0 build /root/script/cloud-reports
> npm install && tsc && cd src/reporters/html && npm install && npm run ng build --  --prod && cd ../../..

npm WARN cloud-reports@0.5.0 No repository field.
src/analyzers/aws/rds/delete_protection_enabled.ts:1:29 - error TS2724: Module '"/root/script/cloud-reports/src/types/index"' has no exported member 'Dictionary'. Did you mean 'IDictionary'?

1 import { CheckAnalysisType, Dictionary, ICheckAnalysisResult, IResourceAnalysisResult, SeverityStatus } from "../../../types";
                              ~~~~~~~~~~


src/analyzers/aws/rds/encryption_enabled.ts:1:64 - error TS2724: Module '"/root/script/cloud-reports/src/types/index"' has no exported member 'ResourceAnalysisResult'. Did you mean 'IResourceAnalysisResult'?

1 import { CheckAnalysisType, ICheckAnalysisResult, IDictionary, ResourceAnalysisResult, SeverityStatus } from "../../../types";
                                                                 ~~~~~~~~~~~~~~~~~~~~~~

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cloud-reports@0.5.0 build: `npm install && tsc && cd src/reporters/html && npm install && npm run ng build --  --prod && cd ../../..`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cloud-reports@0.5.0 build script 'npm install && tsc && cd src/reporters/html && npm install && npm run ng build --  --prod && cd ../../..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cloud-reports package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && tsc && cd src/reporters/html && npm install && npm run ng build --  --prod && cd ../../..
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cloud-reports
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cloud-reports
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/script/cloud-reports/npm-debug.log

**Comment by agnelNandapurapu** [comment]
@sathyajackson, we have fixed errors please try again.

**Comment by koladilip** [comment]
can we close this?

**Comment by sathyajackson** [comment]
when i try to use the -pdf formate i get the report just fine, but when i use -html formate, i end up with below error.

(node:80) UnhandledPromiseRejectionWarning: Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:80) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "scan" "--" "--profile" "default" "-f" "html" "--module" "ec2,s3,ebs,elb"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cloud-reports@0.5.0 scan: `node dist/scan.js "--profile" "default" "-f" "html" "--module" "ec2,s3,ebs,elb"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloud-reports@0.5.0 scan script 'node dist/scan.js "--profile" "default" "-f" "html" "--module" "ec2,s3,ebs,elb"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cloud-reports package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/scan.js "--profile" "default" "-f" "html" "--module" "ec2,s3,ebs,elb"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cloud-reports
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cloud-reports
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/scripts/cloud-reports/npm-debug.log

I am not sure if this is a bug in the code or is this something to do with my OS . Anyways i will try in different operating system and update.

**Comment by koladilip** [comment]
Can you tell us your OS details @sathyajackson ?

**Comment by sathyajackson** [comment]
I have 2 machines, 1 amazon linux and another one is ubuntu 18

**Comment by koladilip** [comment]
@agnelnanda can you test this on amazonlinux and ubuntu 18?

**Comment by agnelNandapurapu** [comment]
I will test and let u know @sathyajackson

**Comment by sathyajackson** [comment]
sure testing it on ubuntu18 for html page.

**Comment by koladilip** [comment]
@sathyajackson HTML dashboard requires GUI, if you are running in command line mode on EC2 you will get error.

**Comment by sathyajackson** [comment]
yes, I am testing in ubuntu which is a standard desktop.

**Comment by agnelNandapurapu** [comment]
@sathyajackson can you tell me ram size for Ubuntu 18?

**Comment by sathyajackson** [comment]
Error i get on my ubuntu machine

{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{ Error: ENOENT: no such file or directory, open 'src/reporters/html/dist/html-report/assets/data.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /root/script/cloud-reports/dist/scan.js:78:26
    at step (/root/script/cloud-reports/dist/scan.js:32:23)
    at Object.next (/root/script/cloud-reports/dist/scan.js:13:53)
    at /root/script/cloud-reports/dist/scan.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/script/cloud-reports/dist/scan.js:3:12)
    at makeFileContents (/root/script/cloud-reports/dist/scan.js:70:12)
    at /root/script/cloud-reports/dist/scan.js:137:42
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/reporters/html/dist/html-report/assets/data.json' }

**Comment by agnelnanda** [comment]
@sathyajackson We have found this issue in ListMfaDevices API call, and we have resolved it. please check now.

**Comment by sumitnair001** [comment]
Did you run the command : "**npm run build**" ? If you are getting an error on that too, go to _/src/reporters/html_ directory and run the command "**npm run ng build -- --prod**" once. After that go back to the main directory and run the scan: " **npm run scan -- -p aws-profile -m iam**". That should clearly give the result.
