### ISSUE TITLE
Dashboard Intergration

### ISSUE THREAD

**Issue by sathyajackson** [tensult/cloud-reports#6]
not sure if I have followed the code properly, but thought of asking this question to the developer, do you have any sort of dashboard integration done for this tool or anything in the roadmap?

I would like to know if this can be used some sort of web server so that the reports can be directly populated on the web server dashboard.

**Comment by koladilip** [comment]
currently this supports standalone dashboards, we are working SAAS based solution where you will give ability to generate reports from anywhere and view the reports in the SAAS solution.

**Comment by sathyajackson** [comment]
oh cool, can you walk share some code links to use the standalone dashboard?

**Comment by koladilip** [comment]
Actually HTML version has dashboard feature which you are facing issues use it. Lets track this in the other issues.

https://github.com/tensult/cloud-reports/issues/5
