### ISSUE TITLE
Getting Timeouts/Failures for the EC2 & RDS checks.  Timeout connecting to .cn endpoints?

### ISSUE THREAD

**Issue by pocketcalculator** [tensult/cloud-reports#62]
I'm getting timeouts for these two modules.  Does the endpoint have any bearing on the failure?  Am I connecting to the right endpoints for this data?

[ERROR] aws.ec2.EC2InstancesCollection failed { Error: connect ETIMEDOUT 54.222.17.62:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
message: 'connect ETIMEDOUT 54.222.17.62:443',
errno: 'ETIMEDOUT',
code: 'NetworkingError',
syscall: 'connect',
address: '54.222.17.62',
port: 443,
region: 'cn-north-1',
hostname: 'ec2.cn-north-1.amazonaws.com.cn',
retryable: true,
time: 2019-06-27T21:40:52.467Z }

**Comment by koladilip** [comment]
.cn endpoints might be restricted by AWS. Do you have workloads in the CN region?
