### ISSUE TITLE
CheckCategory not displaying on few 'view details' from Main Dashboard

### ISSUE THREAD

**Issue by gmmurugan** [tensult/cloud-reports#7]
![tensultcloudreports1](https://user-images.githubusercontent.com/48428/49535538-0d78dc80-f88a-11e8-9eb8-98658e1a6460.gif)

Check the IAM one in the above GIF when it has details to show in checkdetail dashboard
Also, it ran across all collectors and i dont have any resources in that account to scan. but the result should tell at-least like 0/0 or not resource found.

**Comment by paragpoddar** [comment]
@gmmurugan, We have tried with other AWS accounts but did not find this problem. Can you please share any error coming in browser console?

**Comment by koladilip** [comment]
No response so closing.
