### ISSUE TITLE
OnDemand Scan via API from Dashboard(html report)

### ISSUE THREAD

**Issue by gmmurugan** [tensult/cloud-reports#9]
would like to run this app standalone and still call the scan by api call and see them in report(html dashboard). the dashboard can be sourced from the specific scan results.

this feature  will give this tool an on-demand scan report as a web application hosted in aws environment

1.  Convert Scan.js into an API invoke
2. Make the dashboard(html report) to use the last scanned data and keep the archives in local as json and consumed with a combo box

**Comment by koladilip** [comment]
We are not planning for now.

**Comment by koladilip** [comment]
@gmmurugan We have released a SaaS version for this: https://apps.tensult.com/#/home
